### PR TITLE
Ember.View is deprecated and shouldn't be used anymore

### PR DESCRIPTION
**Pull request by rogatty**
`Ember.View` is deprecated in Ember 1.13 and will be removed in Ember 2.0. This PR gets rid of deprecation message and prepares the lib for Ember 2.0. It addresses https://github.com/chriswessels/ember-hammer/issues/13 too.

### CODE REVIEW

**Comment by chriswessels** [comment]
Thanks for this @rogatty!

**Comment by rogatty** [comment]
Can you also create a tag so we can use the new version in bower.json? Thanks :)

**Comment by FredUK** [comment]
@chriswessels @rogatty is right, I'm unable to use bower install ember-hammer to install v.1.0.2. Thanks :)

**Comment by chriswessels** [comment]
Will do!

**Comment by chriswessels** [comment]
`1.0.2` added!

**Comment by FredUK** [comment]
:+1:  Thanks a lot !

**Pull request merged**
